POLYGON_API_KEY = 'YOUR_API_KEY'
WHATSAPP_CONTACT_NUMBER = "YOUR_PHONE_NUMBER"
MAX_RETRIES = 3
INITIAL_WAIT = 60
DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
TICKERS = ['TSLA', 'AAPL', 'MSFT', 'NVDA', 'META', 'AMD', 'INTC', 'GOOGL', 'AMZN', 'NFLX']